### ISSUE TITLE
tag a release, so this can be packaged

### ISSUE THREAD

**Issue by dvzrv** [raboof/realtimeconfigquickscan#24]
It would be great to have this tool packaged (Arch Linux [community])! All I need is a tagged release (preferably in semver) ;-)

**Comment by raboof** [comment]
Packaging would be great!

I think 'releases'  are an antiquated concept, however, and people should just be tracking 'master'.

Is this possible in Arch packaging?

**Comment by dvzrv** [comment]
On 2018-12-04 04:01:41 (-0800), Arnout Engelen wrote:
> I think 'releases'  are an antiquated concept, however, and people
> should just be tracking 'master'.
LOL... seriously? There is nothing antiquated about that.

How would any downstream properly "track" master? Rebuild a package on
every tiny "I fixed a typo" commit?
How does this help with providing stable software? Will you prevent
breakage of the master branch by having no tests whatsoever?
How does this help with non-git-tech-savy people trying to supply bug
reports? Against a commit checksum?

Sorry, but this is complete nonsense.

> Is this possible in Arch packaging?
Not in the official repositories. Not in any official repository of any
distro I'm aware of, unless you're on Yolo Linux ;-)

**Comment by raboof** [comment]
> LOL... seriously?

OK, maybe (just maybe :smile:) I was exaggerating, but I'm half-serious.

> Rebuild a package on every tiny "I fixed a typo" commit?

Sure, on every merge to master, why not? Automate the hell out of it. If you don't want to, well, then don't - no problem there.

> How does this help with providing stable software?

It helps because it gets any changes in the hands of users sooner, removing the barrier of "I should really cut a release but <insert excuse of the day here>". If a change isn't stable, it has no business getting merged to master.

If a user does run into a bug, it will get found and fixed faster, because it is probably a recent change rather than "one of the many changes since the previous release years ago".

It will make it easier for users to get involved in reporting, diagnosing an fixing the problem - which is part of the point of open source, if you ask me.

> Will you prevent breakage of the master branch by having no tests whatsoever?

I agree it's not great that this project doesn't have any automated tests - contributions welcome!

Did you see any breakage so far, though? Let's not make this problem sound any larger than it really is.

> How does this help with non-git-tech-savy people trying to supply bug reports? Against a commit checksum?

Why not? OK, to easily keep track of 'how old a build is' a `git describe`-like version (counting the number of commits to master since the inception of the project, or since the previous 'epoch' version) could be used. 

> Not in any official repository of any distro I'm aware of, unless you're on Yolo Linux ;-)

Sign me up for Yolo Linux :smile:
