### ISSUE TITLE
simplified version

### ISSUE THREAD

**Issue by grammoboy2** [raboof/realtimeconfigquickscan#33]
Still a useful script. 

Some suggested system changes are open for discussion it seems though. Maybe add a simplified version of the script, with the most important checks? So you can point newbies to that simplified script, as a method to get your linux distro up and running for audio quickly.

**Comment by raboof** [comment]
Yeah, or maybe split the output in 2 parts? PR welcome :)

**Comment by grammoboy2** [comment]
split output might be even a better idea indeed. Newbie and Nerd column ;)

For instance, I do skip the hardware timer stuff myself, because there 
seems to be doubts about it when I read the wiki.

**Comment by RattusSolarus** [comment]
I just started a thread on LAU mailing list about hardware timers. Got a reply from Clemens Ladisch:-
"Setting max-user-freq for RTC or HPET would be required only if some
application actually accessed these devices directly from user space.
As far as I know, nobody ever did this (because ALSA has its own timer
abstraction), so this has never been applicable."
So it would seem the HW timers bit in the script and the wiki may be irrelevant.
The wiki is out of date in other aspects too. For one, it assumes system uses sysvinit and scaling governor can be set in /etc/rc.local . With systemd it can be set in a service file. I've noticed performance governor doesn't set the max cpu frequency like it used to but varies a little eg. 2.8-3.17GHz on my nominal 3.16GHz cpu. No idea what that's about.

**Comment by raboof** [comment]
PR's welcome :D

**Comment by RattusSolarus** [comment]
I only know enough about this stuff to be dangerous which is why I want to be cautious about PRs. The HW timer bit would seem to be cut and dried, but I'm less confident about the scaling governor.
I'll PR later today and remove HW timers. It will simplify the script which is why I posted in this issue whereas I actually logged intending to start a new one.

**Comment by RattusSolarus** [comment]
I don't know Perl really but find it easier to understand than git. PR submitted.

**Comment by raboof** [comment]
I think these PR's are now merged
